<div style="background-color: white; width: 100%; height: 10px"></div>
<div class="footer-container">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                Адрес: ул. Тритузная, 69, г. Каменское, <br>Днепропетровская обл., 51918,
                <br/>Украина
                <br/><span style="text-transform: lowercase;">e-mail:&nbsp;<a href="mailto:at-spectr@i.ua">at-spectr@i.ua</a></span>
            </div>
            <div class="col-sm-6">
                Телефоны:
                <br/>+38 (067) 568 08 63 <span style="text-transform: lowercase;">(многоканальный)</span>
                <br/>+38 (056) 958 89 97 
                <br/>+38 (056) 958 84 91
            </div>
        </div>
    </div>
</div>
